@url = http://localhost:5000/users-module
@email = user1@confab.io
@password = secret
@role = user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjhlNjM2NC0wOGMxLTQ4ZjEtYjAzZC0wMWE3NzcyNGFmYjQiLCJ1bmlxdWVfbmFtZSI6IjZmOGU2MzY0LTA4YzEtNDhmMS1iMDNkLTAxYTc3NzI0YWZiNCIsImp0aSI6IjIwMThlYTJhLTQwODQtNDk5Yi1hOWY2LWEyZjM3ZDdlZTZjZCIsImlhdCI6IjE2MTkwOTQyMDEyMTgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTYxOTA5NDIwMSwiZXhwIjoxNjE5MTMwMjAxLCJpc3MiOiJjb25mYWIifQ.bQTlQaO24xbGjNl9MVf5wJiNCr2r91TL2v8rQ_jvZfA
###
GET {{url}}

###
GET {{url}}/account
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "role": "{{role}}",
  "claims": {
    "permissions": ["conferences", "hosts", "speakers", "tickets", "users"]
  }
}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}